swagger: "2.0"
info:
  description: "This microservice handles request to add/remove likes and dislikes and retrieve a list of stories we are interacted with (used by Rank microservice)"
  version: "1.0.0"
  title: "Reactions Microservice"
schemes:
- "http"
paths:
  /like:
    post:
      summary: "Add like to a story"
      operationId: like
      consumes: 
      - "application/json"
      parameters:
      - in : "body"
        name: "body"
        required: true
        description: Object containing user_id and story_id
        schema:
          $ref: "#/definitions/Reaction"
      responses:
        '200':
          description: "Like added"
        '400':
          description: "Malformed request"
        '409':
          description: "Story already liked"
        '404':
          description: "Story not found"
    delete:
        summary: "Delete like from a story"
        operationId: remove_like
        consumes: 
        - "application/json"
        parameters:
        - in : "body"
          name: "body"
          required: true
          description: Object containing user_id and story_id
          schema:
            $ref: "#/definitions/Reaction"
        responses:
          '200':
            description: "Like removed"
          '400':
            description: "Malformed request"
          '409':
            description: "No like to remove"
          '404':
          description: "Story not found"

  /dislike:
    post:
      summary: "Add dislike to a story"
      operationId: dislike
      consumes: 
      - "application/json"
      parameters:
      - in : "body"
        name: "body"
        required: true
        description: Object containing user_id and story_id
        schema:
          $ref: "#/definitions/Reaction"
      responses:
        '200':
          description: "Dislike added"
        '400':
          description: "Malformed request"
        '409':
          description: "Story already disliked"
        '404':
          description: "Story not found"
    delete:
      summary: "Delete dislike from a story"
      operationId: remove_dislike
      consumes: 
      - "application/json"
      parameters:
      - in : "body"
        name: "body"
        required: true
        description: Object containing user_id and story_id
        schema:
          $ref: "#/definitions/Reaction"
      responses:
        '200':
          description: "Dislike removed"
        '400':
          description: "Malformed request"
        '409':
          description: "No dislike to remove"
        '404':
          description: "Story not found"
  
  /get-reacted-stories/{user-id}:
    get:
      summary: "Retrieve a list of stories we are interacted with (used by Rank microservice)"
      description: "used by Rank microservice only"
      operationId: getReactedStories
      produces: 
      - "application/json"
      parameters:
      - in: "path"
        name: "user-id"
        required: true
        type: "integer"
      responses:
        '200':
          description: "List successfully given"
          schema:
            $ref: '#/definitions/Stories_id'
        '400':
          description: "Malformed request"
          
definitions:
  Reaction:
    type: "object"
    properties:
      user_id:
        type: "integer"
      story_id:
        type: "integer"
    required:
    - "story_id"
    - "user_id"
    additionalProperties: false
    xml:
      name: "Reaction"
      
  Stories_id:
    type: "object"
    properties:
      stories_id:
        type: "array"
        items:
          type: "integer"
    required:
    - "stories_id"
    additionalProperties: false
    xml:
      name: "Stories_id"
